name: edukids_app
description: "Una aplicación pedagógica móvil para ayudar a niños con la lectura y escritura."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  firebase_core: ^3.1.0      
  firebase_auth: ^5.1.0      
  cloud_firestore: ^5.0.1    
  
  flutter_tts: ^4.0.2
  audioplayers: ^6.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logo.png
    - assets/audio/musica_fondo.mp3  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21