// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChiku7oLTckM3WjaPB6DffrtxXYDuUuwg',
    appId: '1:369506880574:web:f5eac6a624c4c41837956f',
    messagingSenderId: '369506880574',
    projectId: 'edukids-app-6146b',
    authDomain: 'edukids-app-6146b.firebaseapp.com',
    storageBucket: 'edukids-app-6146b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK9pOtr4NsN7rDw7FwGJElMo-Qfh5Ky-o',
    appId: '1:369506880574:android:a288fcf96c7cb36637956f',
    messagingSenderId: '369506880574',
    projectId: 'edukids-app-6146b',
    storageBucket: 'edukids-app-6146b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9kpEF-eAb2MqWmHhfuwX4fAGdI2lrT4w',
    appId: '1:369506880574:ios:1a896430a8aeb85d37956f',
    messagingSenderId: '369506880574',
    projectId: 'edukids-app-6146b',
    storageBucket: 'edukids-app-6146b.firebasestorage.app',
    iosBundleId: 'com.example.edukidsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9kpEF-eAb2MqWmHhfuwX4fAGdI2lrT4w',
    appId: '1:369506880574:ios:1a896430a8aeb85d37956f',
    messagingSenderId: '369506880574',
    projectId: 'edukids-app-6146b',
    storageBucket: 'edukids-app-6146b.firebasestorage.app',
    iosBundleId: 'com.example.edukidsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChiku7oLTckM3WjaPB6DffrtxXYDuUuwg',
    appId: '1:369506880574:web:f74c154084386fe337956f',
    messagingSenderId: '369506880574',
    projectId: 'edukids-app-6146b',
    authDomain: 'edukids-app-6146b.firebaseapp.com',
    storageBucket: 'edukids-app-6146b.firebasestorage.app',
  );
}
